export const emails = [
  {
    from: "John Doe",
    subject: "Welcome to Gmail!",
    body: "Hi there,\n\nWelcome to your new Gmail account! We're excited to have you on board.\n\n- The Gmail Team",
    unread: true,
    time: "6.40 pm",
  },
  {
    from: "Jane Smith",
    subject: "Re: Project Update",
    body: "Hi John,\n\nJust wanted to check in on the project status. Any updates?",
    unread: true,
    time: "5.40 pm",
  },
  {
    from: "Amazon",
    subject: "Your order has shipped!",
    body: "Hi John,\n\nYour order has been shipped and is on its way. You can track it here: https://...",
    unread: true,
    time: "1.40 pm",
  },
  {
    from: "Google Photos",
    subject: "Check out your latest memories",
    body: "Hi John,\n\nWe've created a new album of your latest photos. Take a look: https://...",
    unread: true,
    time: "5.40 pm",
  },
  {
    from: "Netflix",
    subject: "New shows you might like",
    body: "Hi John,\n\nHere are some new shows we think you'll enjoy: \n- Stranger Things \n- The Witcher \n- Squid Game",
    unread: true,
    time: "7.40 pm",
  },
  {
    from: "Facebook",
    subject: "See what your friends are up to",
    body: "Hi John,\n\nCatch up on the latest posts from your friends and family. See what's happening now: https://...",
    unread: true,
    time: "2.40 pm",
  },
  {
    from: "LinkedIn",
    subject: "New job opportunities for you",
    body: "Hi John,\n\nWe've found some jobs that might be a good fit for your skills and experience. Check them out: https://...",
    unread: true,
    time: "10.40 am",
  },
  {
    from: "Spotify",
    subject: "Discover new music you'll love",
    body: "Hi John,\n\nHere are some personalized playlists we've created for you based on your listening history: https://...",
    unread: true,
    time: "4.40 pm",
  },
  {
    from: "YouTube",
    subject: "New videos from your favorite channels",
    body: "Hi John,\n\nDon't miss the latest videos from the channels you subscribe to. Watch now: https://...",
    unread: true,
    time: "8.40 pm",
  },
  {
    from: "Instagram",
    subject: "See new posts from people you follow",
    body: "Hi John,\n\nThere are new photos and videos from the people you follow. Check them out: https://...",
    unread: true,
    time: "12.40 pm",
  },
  {
    from: "Twitter",
    subject: "See what's happening in the world",
    body: "Hi John,\n\nStay up-to-date on the latest news, trends, and conversations. See what's happening now: https://...",
    unread: true,
    time: "9.40 am",
  },
  {
    from: "Bank of America",
    subject: "Your monthly statement is ready",
    body: "Hi John,\n\nYour monthly statement is now available online. View it here: https://...",
    unread: true,
    time: "3.40 pm",
  },
  {
    from: "Uber",
    subject: "Your ride is on its way",
    body: "Hi John,\n\nYour Uber is 5 minutes away. Track your driver's progress here: https://...",
    unread: true,
    time: "6.40 pm",
  },
  {
    from: "DoorDash",
    subject: "Your food is being delivered",
    body: "Hi John,\n\nYour food is on its way! Track your delivery here: https://...",
    unread: true,
    time: "7.40 pm",
  },
  {
    from: "Amazon Prime",
    subject: "Your package has been delivered",
    body: "Hi John,\n\nYour package has been delivered to your doorstep. Enjoy! https://...",
    unread: true,
    time: "11.40 am",
  },
];
